export function getFrenchVerb(number: number): string {
    const frenchVerbs: Record<number, string> = {
        1: 'Accepter',
        2: 'Acheter',
        3: 'Adorer',
        4: 'Aider',
        5: 'Aimer',
        6: 'Ajouter',
        7: 'Amener',
        8: 'Améliorer',
        9: 'Appeler',
        10: 'Apporter',
        11: 'Approcher',
        12: 'Approuver',
        13: 'Appuyer',
        14: 'Arrêter',
        15: 'Arriver',
        16: 'Assassiner',
        17: 'Assurer',
        18: 'Attacher',
        19: 'Attraper',
        20: 'Avancer',
        21: 'Bouger',
        22: 'Booster',
        23: 'Briller',
        24: 'Brûler',
        25: 'Cacher',
        26: 'Capter',
        27: 'Causer',
        28: 'Charger',
        29: 'Charmer',
        30: 'Cesser',
        31: 'Changer',
        32: 'Charmer',
        33: 'Charger',
        34: 'Chercher',
        35: 'Chauffer',
        36: 'Cliquer',
        37: 'Coller',
        38: 'Cogner',
        39: 'Commencer',
        40: 'Compter',
        41: 'Contester',
        42: 'Continuer',
        43: 'Copier',
        44: 'Coucher',
        45: 'Couper',
        46: 'Crier',
        47: 'Croiser',
        48: 'Cultiver',
        49: 'Danser',
        50: 'Décider',
        51: 'Déjeuner',
        52: 'Demander',
        53: 'Détacher',
        54: 'Détester',
        55: 'Deviner',
        56: 'Dîner',
        57: 'Donner',
        58: 'Écouter',
        59: 'Échouer',
        60: 'Élever',
        61: 'Embrasser',
        62: 'Emmener',
        63: 'Emporter',
        64: 'Ennuyer',
        65: 'Enregister',
        66: 'Entrer',
        67: 'Envoyer',
        68: 'Espérer',
        69: 'Essayer',
        70: 'Essuyer',
        71: 'Étudier',
        72: 'Exciter',
        73: 'Exister',
        74: 'Expliquer',
        75: 'Exprimer',
        76: 'Excuser',
        77: 'Fermer',
        78: 'Fêter',
        79: 'Filmer',
        80: 'Flouter',
        81: 'Forcer',
        82: 'Former',
        83: 'Frapper',
        84: 'Gagner',
        85: 'Garder',
        86: 'Gêner',
        87: 'Guider',
        88: 'Glisser',
        89: 'Habiter',
        90: 'Informer',
        91: 'Inquiéter',
        92: 'Insister',
        93: 'Inspirer',
        94: 'Inviter',
        95: 'Jeter',
        96: 'Jouer',
        97: 'Juger',
        98: 'Laisser',
        99: 'Kiffer',
        100: 'Lever',
        101: 'Manger',
        102: 'Manquer',
        103: 'Marcher',
        104: 'Mener',
        105: 'Monter',
        106: 'Montrer',
        107: 'Mouiller',
        108: 'Nager',
        109: 'Négocier',
        110: 'Nier',
        111: 'Nommer',
        112: 'Occuper',
        113: 'Oublier',
        114: 'Parler',
        115: 'Passer',
        116: 'Payer',
        117: 'Pencher',
        118: 'Penser',
        119: 'Placer',
        120: 'Pleurer',
        121: 'Porter',
        122: 'Poser',
        123: 'Posséder',
        124: 'Pousser',
        125: 'Préférer',
        126: 'Préparer',
        127: 'Présenter',
        128: 'Prêter',
        129: 'Prier',
        130: 'Promener',
        131: 'Prononcer',
        132: 'Protéger',
        133: 'Quitter',
        134: 'Raconter',
        135: 'Rappeler',
        136: 'Rapporter',
        137: 'Rassembler',
        138: 'Réceptionner',
        139: 'Refuser',
        140: 'Regarder',
        141: 'Rencontrer',
        142: 'Rentrer',
        143: 'Répéter',
        144: 'Reporter',
        145: 'Respirer',
        146: 'Ressembler',
        147: 'Rester',
        148: 'Retourner',
        149: 'Retrouver',
        150: 'Rêver',
        151: 'Rouler',
        152: 'Sauvegarder',
        153: 'Sauver',
        154: 'Sembler',
        155: 'Tacher',
        156: 'Tasser',
        157: 'Télécharger',
        158: 'Téléphoner',
        159: 'Tirer',
        160: 'Tomber',
        161: 'Toucher',
        162: 'Tourner',
        163: 'Tracer',
        164: 'Transpirer',
        165: 'Travailler',
        166: 'Traverser',
        167: 'Tricher',
        168: 'Trier',
        169: 'Tromper',
        170: 'Trouver',
        171: 'Tuer',
        172: 'Violer',
        173: 'Visser',
        174: 'Voler',
        175: 'Voyager',
    };
    
    if (number in frenchVerbs) {
      return frenchVerbs[number];
    } else {
      return 'Out of Range';
    }
  }
  
export function getEnglishVerb(number:number): string {
    const englishVerbs: Record<number, string> = {    
        1: 'Accept',
        2: 'Buy',
        3: 'Love',
        4: 'Help',
        5: 'Like',
        6: 'Add',
        7: 'Bring',
        8: 'Improve',
        9: 'Call',
        10: 'Bring',
        11: 'Approach',
        12: 'Approve',
        13: 'Support',
        14: 'Stop',
        15: 'Arrive',
        16: 'Assassinate',
        17: 'Ensure',
        18: 'Attach',
        19: 'Catch',
        20: 'Advance',
        21: 'Move',
        22: 'Boost',
        23: 'Shine',
        24: 'Burn',
        25: 'Hide',
        26: 'Capture',
        27: 'Cause',
        28: 'Load',
        29: 'Charm',
        30: 'Cease',
        31: 'Change',
        32: 'Charm',
        33: 'Charge',
        34: 'Search',
        35: 'Heat',
        36: 'Click',
        37: 'Paste',
        38: 'Hit',
        39: 'Begin',
        40: 'Count',
        41: 'Challenge',
        42: 'Continue',
        43: 'Copy',
        44: 'Lie down',
        45: 'Cut',
        46: 'Shout',
        47: 'Cross',
        48: 'Cultivate',
        49: 'Dance',
        50: 'Decide',
        51: 'Have lunch',
        52: 'Ask',
        53: 'Detach',
        54: 'Hate',
        55: 'Guess',
        56: 'Have dinner',
        57: 'Give',
        58: 'Listen',
        59: 'Fail',
        60: 'Raise',
        61: 'To kiss',
        62: 'To take (someone)',
        63: 'To take away',
        64: 'To annoy',
        65: 'To record',
        66: 'To enter',
        67: 'To send',
        68: 'To hope',
        69: 'To try',
        70: 'To wipe',
        71: 'To study',
        72: 'To excite',
        73: 'To exist',
        74: 'To explain',
        75: 'To express',
        76: 'To excuse',
        77: 'To close',
        78: 'To celebrate',
        79: 'To film',
        80: 'To blur',
        81: 'To force',
        82: 'To train',
        83: 'To hit',
        84: 'To win',
        85: 'To keep',
        86: 'To bother',
        87: 'To guide',
        88: 'To slide',
        89: 'To live',
        90: 'To inform',
        91: 'To worry',
        92: 'To insist',
        93: 'To inspire',
        94: 'To invite',
        95: 'To throw',
        96: 'To play',
        97: 'To judge',
        98: 'To let',
        99: 'To love',
        100: 'To lift',
        101: 'To eat',
        102: 'To miss',
        103: 'To walk',
        104: 'To lead',
        105: 'To climb',
        106: 'To show',
        107: 'To wet',
        108: 'To swim',
        109: 'To negotiate',
        110: 'To deny',
        111: 'To name',
        112: 'To occupy',
        113: 'To forget',
        114: 'To speak',
        115: 'To pass',
        116: 'To pay',
        117: 'To lean',
        118: 'To think',
        119: 'To place',
        120: 'To cry',
        121: 'To carry',
        122: 'To pose',
        123: 'To possess',
        124: 'To push',
        125: 'To prefer',
        126: 'To prepare',
        127: 'To present',
        128: 'To lend',
        129: 'To pray',
        130: 'To walk (someone/something)',
        131: 'To pronounce',
        132: 'To protect',
        133: 'To leave',
        134: 'To tell',
        135: 'To remind',
        136: 'To report',
        137: 'To gather',
        138: 'To receive',
        139: 'To refuse',
        140: 'To watch',
        141: 'To meet',
        142: 'To come back',
        143: 'To repeat',
        144: 'To postpone',
        145: 'To breathe',
        146: 'To resemble',
        147: 'To stay',
        148: 'To return',
        149: 'To find again',
        150: 'To dream',
        151: 'To roll',
        152: 'To save (data)',
        153: 'To save',
        154: 'To seem',
        155: 'To stain',
        156: 'To compact',
        157: 'To download',
        158: 'To call',
        159: 'To pull',
        160: 'To fall',
        161: 'To touch',
        162: 'To turn',
        163: 'To trace',
        164: 'To sweat',
        165: 'To work',
        166: 'To cross',
        167: 'To cheat',
        168: 'To sort',
        169: 'To deceive',
        170: 'To find',
        171: 'To kill',
        172: 'To violate',
        173: 'To screw',
        174: 'To steal',
        175: 'To travel'
    }

    if (number in englishVerbs) {
        return englishVerbs[number];
      } else {
        return 'Out of Range';
      }
}